### ISSUE TITLE
missing functionalities in vendor claim management

### ISSUE THREAD

**Issue by ccandito** [OCA/rma#99]
in case of vendor claim should be possible:
1) to enter the claim reference in asking refund form (credit memo) so this is collected in the claim form;
2) change the qty in product returns for partial return delivery back to the vendor
3) close the status of the related claim line
Regards
claudio candito

**Comment by ccandito** [comment]
Dear All,
for the sake of clarity, I'd provide more exhaustive description:
1) the credit memo form should be enhanced with the same feature in goods movements, i.d. the possibility to enter the claim reference; in that way the credit memo created out of the claim form can be collected in the claim form.
2) the claim line qty could be changeable so partial return can be managed also
3) how it is possible to close the claim line status: it seems no feature is available for the time being.
Regards
claudio Candito

**Comment by rubencabrera** [comment]
About (2), I'm always getting qty = 0 for every return line. The same happens for Unit sale price and Total Return (return_value).
Is this happening to you too?

**Comment by aitorbouzas** [comment]
@ccandito agree with this post. There's no way this module can be used properly... You can't change line status, the product_returned_quantity is always zero...

@rubencabrera Yes, this is happening to everyone. I found that if you place the "product_returned_quantity" in the tree view of the crm.claim form it is correctly filled... But it doesn't matter because there's no functionality to use line status.

**Comment by JordiBForgeFlow** [comment]
Hi! We are completely redesigning the rma app. In a few days we will create a PR and webinars to discuss.

cc @aheficent
